cantries = ['italy', 'france', 'japan', 'spain', 'usa', 'australia']
print(sorted(cantries))
print(cantries)
cantries.reverse()
print(cantries)
cantries.reverse()
print(cantries)
cantries.sort()
print(cantries)
cantries.sort(reverse=True)
print(cantries)