names = ['anna', 'viktor', 'tany', 'dima', 'julya', 'denis', 'olya', 'nukita', 'kostya']
print(sorted(names))
print(names)
names.sort()
print(names)
names.sort(reverse=True)
print(names)
print(len(names))
names.reverse()
print(names)
print(names[8])